Faq Content Added
ManishBisht777/frontend-freaks-website pull request #37
Opened 2023-07-22 16:22 UTC by sujitmemane

Content Updation of Website based on previous website and notion

2023-07-23 13:25 UTC, ManishBisht777 requested changes
left some comments

2023-07-23 13:25 UTC, ManishBisht777 commented on components/faq.tsx
> +            If you're confident in your HTML, CSS, and JavaScript skills, join batch 2 to learn ReactJS. Otherwise, start with batch 1 to establish a solid foundation before diving into ReactJS. If y
the `'` in `you're` is causing build error

2023-07-23 14:30 UTC, sujitmemane commented on components/faq.tsx
> +            If you're confident in your HTML, CSS, and JavaScript skills, join batch 2 to learn ReactJS. Otherwise, start with batch 1 to establish a solid foundation before diving into ReactJS. If y
ok Got it

2023-08-05 05:59 UTC, ManishBisht777 approved these changes
LGTM

2023-08-05 05:59 UTC, merged